name: FluidNC Release Builder

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release version'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set release version
      run: |
        git config user.email "wmb@firmworks.com"
        git config user.name "Mitch Bradley"
        git tag "${{ github.event.inputs.tag }}" -a -m "Release test"
    - name: Build
      run: python build-release.py
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/current
        repository-name: MitchBradley/MitchBradley.github.io
        ssh-key: ${{ secrets.GHP_DEPLOY_KEY }}
        target-folder: releases/${{ github.event.inputs.tag }}
